openapi: 3.0.3
info:
  title: MyBank REST API
  description: |-
    This is a **Banking REST API**, this API includes three domains, Security Domain, Customer Domain and Account Domain, its design it's based on the Open Api Specification 3.0.
  contact:
    email: aline.perez@3pillarglobal.com
  license:
    name: MyBank License
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://mybank/api/v1
tags:
  - name: security
    description: Authentication resources
  - name: customer
    description: CRUD Catalog to manage customer information
  - name: account
    description: CRUD Catalog to manage account information
paths:
### Security domain ###
  # Authentication service validation for username and password
  /login:
    get:
      tags:
        - security
      summary: Authentication service validation for username and password
      description: Login service with user and password
      operationId: login
      parameters:
        - $ref: '#/components/parameters/username'
        - $ref: '#/components/parameters/password'
      responses:
        '200':
          description:  Successful Login. Valid user and password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnLoginSuccessResponse'
        '401':
          $ref: '#/components/responses/authenticationFailed'
        '500':
          $ref: '#/components/responses/5xxError'
### Customer domain ###
  # Creates a new customer
  /customer:
    post:
      tags:
        - customer
      summary: Resource in charge of customer creation
      description: Create a new customer
      operationId: createCustomer
      security:
      - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        '201':
          description: The customer was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnSuccessResponse'
          links: 
            getOrderById:
              $ref: '#/components/links/getCustomerById'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/5xxError'
    # Modify a customer
    put:
      tags: 
        - customer
      summary: Resource that modifies customer data
      description: Update customer details
      operationId: updateCustomer
      security:
      - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        '200':
          description: Customer was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnSuccessResponse'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/5xxError'
  # Retreives a custumer by ID
  /customer/{customerId}:
    get:
      tags:
        - customer
      summary: Resource that retrieves a customer by ID
      description: Find customer by ID
      operationId: getCustomerById
      security:
      - BasicAuth: []
      parameters:
        - $ref: '#/components/parameters/customerId'
      responses:
        '200':
          description: Customer was successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnQueryCustomerResponse'         
        '400':
          $ref: '#/components/responses/400Error'
        '404':
          $ref: '#/components/responses/404Error'
    # Delete a customer by ID      
    delete:
      tags:
        - customer
      summary: Resource that delete customer by ID
      description: Delete customer by ID
      operationId: deleteCustomer
      security:
      - BasicAuth: []
      parameters:
        - $ref: '#/components/parameters/customerId'
      responses:
        '204':
          description: Customer was deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnSuccessResponse'
        '400':
          $ref: '#/components/responses/400Error'
        '404':
          $ref: '#/components/responses/404Error'
### Account domain ###
  # Create new account
  /account: 
    post:
      tags: 
        - account
      summary: Resource in charge of account creation
      description: Add a new account
      operationId: createAccount
      security:
      - BasicAuth: []
      requestBody:
        description: Create a new account for a client
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        '201':
          description: Account was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnSuccessResponse'
          links: 
            getAccountByAccountNumber:
              $ref: '#/components/links/getAccountByAccountNumber'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/5xxError'
  # Modify an account
    put:
      tags: 
        - account
      summary: Resource that modifies account data
      description: Update account details
      operationId: updateAccount
      security:
      - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        required: true
      responses:
        '200':
          description: Account was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnSuccessResponse'
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/5xxError'
  # Retreives an account by aacount number
  /account/{accountNumber}:
    get:
      tags:
        - account
      summary: Resource that retrieves an account by account number
      description: Find account by account number
      operationId: getAccountByAccountNumber
      security:
      - BasicAuth: []
      parameters:
        - $ref: '#/components/parameters/accountNumber'
      responses:
        '200':
          description: Account was successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnQueryAccountResponse'        
        '400':
          $ref: '#/components/responses/400Error'
        '404':
          $ref: '#/components/responses/404Error'  
    # Delete an account by account number   
    delete:
      tags:
        - account
      summary: Resource that delete account by account number
      description: Delete account by account number
      operationId: deleteAccount
      security:
      - BasicAuth: []
      parameters:
        - $ref: '#/components/parameters/accountNumber'
      responses:
        '204':
          description: Customer was deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnSuccessResponse'
        '400':
          $ref: '#/components/responses/400Error'
        '404':
          $ref: '#/components/responses/404Error'
components:
### Parameters ###
  parameters:
    # user name parameter for login
    username:
      name: username
      in: query
      description: User name for login
      required: true
      schema:
        type: string
        minLength: 10
        example: A45TR67YZ0
    # Login password
    password:
      name: password
      in: query
      description: Password needed for login
      required: true
      schema:
        type: string
        format: password
        minLength: 10
        example: #CDfr546#@
    # Account number
    accountNumber:
      name: accountNumber
      in: path
      description: Account identifier
      required: true
      schema:
        type: integer
        format: int64
    # Customer identifier
    customerId:
      name: customerId
      in: path
      description: Customer identifier
      required: true
      schema:
        type: integer
        format: int64
### Schemas ###
  schemas:
    # schema - Customer object
    Customer:
     type: object
     properties:
      custumerName:
        type: string
        example: Daniel Sanchez
      birthDate:
        type: string
        format: date
        example: 15/10/1990
      active:
        type: boolean
        example: true
      atDate:
        type: boolean
        example: false
      bankingAccounts:
        type: array
        items:
           $ref: '#/components/schemas/Account'
    # schema - Account object
    Account:
     type: object
     properties:
      accountNumber:
       type: integer
       format: int64
       example: 2546132012563
      accountType:
       type: string
       description: Account type (two options)
       example: Saving
       enum:
        - saving
        - checking
      balance:
       type: number
       format: float
       example: 15300.25
      overdraftAllowed: 
       type: boolean
       description: Flag to show if account allows overdrafts 
       example: true
      overdraftAmount: 
       type: number
       format: float
       example: 5633.99
    # schema - API Responses <<General>>
    GeneralResponse:
      description: General response to be used for other responses
      type: object
      properties:
        messageCode:
          type: string
          example: C101
        messageDescription:
          type: string
          example: Message Description
    # schema - 4xx && 5xx responses
    OnErrorResponse:
      description: Response returned when an error occurred
      type: object
      properties:
        messageCode:
          type: string
          example: E144
        messageDescription:
          type: string
          example: Error Message Description
        errorType:
          type: string
          description: Error type for internal use
          example: An specific error type
    # schema - On success resource responses for Customer an Account domains
    # Returns the obhect identifier
    OnSuccessResponse:
      description: Response returned when an new object is created
      allOf:
        - $ref: '#/components/schemas/GeneralResponse'
        - type: object
          properties:
            objectId:
              description: New object identifier
              type: number
              format: int64
              example: 18666
    # schema - Query resource response (Customer)
    OnQueryCustomerResponse:
      description: Response returned when a customer is retrieved
      allOf:
        - $ref: '#/components/schemas/GeneralResponse'
        - $ref: '#/components/schemas/Customer'
    # schema - Query resource response (Account)
    OnQueryAccountResponse:
      description: Response returned when an account is retrieved
      allOf:
        - $ref: '#/components/schemas/GeneralResponse'
        - $ref: '#/components/schemas/Account'
    # schema - Login resource response
    OnLoginSuccessResponse:
      description: Response returned when an user is logged in
      type: object
      properties:
        messageCode:
          type: string
          example: S102
        messageDescription:
          type: string
          example: Successful Login
        lastLogin:
          description: Last login date
          type: string
          format: date-time
          example: 2022-09-21T17:32:28Z
    # schema - Login error
    OnLoginErrorResponse:
      description: Response returned when an error occurred in Login
      type: object
      properties:
        messageCode:
          type: string
          example: L107
        messageDescription:
          type: string
          example: Authentication failed. Please check your username and password.
        errorType:
          type: string
          description: Error type for internal use
          example: Authentication failed. User not found.
### Responses ###
  responses:
    # Successful Login
    loginSuccess:
        description:  Successful Login. Valid user and password
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnLoginSuccessResponse'
    # Authentication failed
    authenticationFailed:
        description: Authentication failed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnLoginErrorResponse'
    # 500 response code
    5xxError:
        description: Server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnErrorResponse'
    # 400 response code
    400Error:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OnErrorResponse'
    # 404 response code
    404Error:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OnErrorResponse'
### Links ###
  links:
    getCustomerById:
      description: The retrieved id serves as input for the get resource.
      operationId: getCustomerById
      parameters:
        customerId: '$response.body#/objectId'
    getAccountByAccountNumber:
      description: The retrieved id serves as input for the get resource.
      operationId: getCustomerById
      parameters:
        accountNumber: '$response.body#/objectId'
### Security ###
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic